/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejava;

/**
 *
 * @author Rafael Assis
 */
public class Frm_Calc_Mat extends javax.swing.JFrame {

    /**
     * Creates new form Calc_Mat
     */
    public Frm_Calc_Mat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T_Painel = new javax.swing.JPanel();
        N_Rotulo = new javax.swing.JLabel();
        T_Numero = new javax.swing.JTextField();
        T_Calc = new javax.swing.JButton();
        T_Clear = new javax.swing.JButton();
        T_Resultado = new java.awt.List();
        G_Painel = new javax.swing.JPanel();
        G_Rotulo = new javax.swing.JLabel();
        G_Numero = new javax.swing.JTextField();
        G_Calc = new javax.swing.JButton();
        G_Clear = new javax.swing.JButton();
        G_Sen = new javax.swing.JLabel();
        G_Cos = new javax.swing.JLabel();
        G_Sen_Res = new javax.swing.JLabel();
        G_Cos_Res = new javax.swing.JLabel();
        Fat_Painel = new javax.swing.JPanel();
        Fat_Rotulo = new javax.swing.JLabel();
        Fat_Numero = new javax.swing.JTextField();
        Fat_Calc = new javax.swing.JButton();
        Fat_Clear = new javax.swing.JButton();
        Fat_Res_Rotulo = new javax.swing.JLabel();
        Fat_Res = new javax.swing.JLabel();
        Mult_Painel = new javax.swing.JPanel();
        Mult_Rotulo = new javax.swing.JLabel();
        Mult_Numero = new javax.swing.JTextField();
        Mult_Calc = new javax.swing.JButton();
        Mult_Clear = new javax.swing.JButton();
        Mult_Dobro_Rotulo = new javax.swing.JLabel();
        Mult_Dobro_Res = new javax.swing.JLabel();
        Mult_Triplo_Rotulo = new javax.swing.JLabel();
        Mult_Triplo_Res = new javax.swing.JLabel();
        Mult_Quadruplo_Rotulo = new javax.swing.JLabel();
        Mult_Quadruplo_Res = new javax.swing.JLabel();
        Mult_Quintuplo_Rotulo = new javax.swing.JLabel();
        Mult_Quintuplo_Res = new javax.swing.JLabel();
        Pot_Painel = new javax.swing.JPanel();
        Pot_Rotulo = new javax.swing.JLabel();
        Pot_Numero = new javax.swing.JTextField();
        Pot_Calc = new javax.swing.JButton();
        Pot_Clear = new javax.swing.JButton();
        Pot_Qadrado_Rotulo = new javax.swing.JLabel();
        Pot_Quadrado_Res = new javax.swing.JLabel();
        Pot_Cubo_Rotulo = new javax.swing.JLabel();
        Pot_Cubo_Res = new javax.swing.JLabel();
        Pot_4pot_Rotulo = new javax.swing.JLabel();
        Pot_4pot_Res = new javax.swing.JLabel();
        Pot_5pot_Rotulo = new javax.swing.JLabel();
        Pot_5pot_Res = new javax.swing.JLabel();
        Pot_6pot_Rotulo = new javax.swing.JLabel();
        Pot_6pot_Res = new javax.swing.JLabel();
        Pot_7pot_Rotulo = new javax.swing.JLabel();
        Pot_7pot_Res = new javax.swing.JLabel();
        Med_Painel = new javax.swing.JPanel();
        Med_Calc = new javax.swing.JButton();
        Med_Clear = new javax.swing.JButton();
        Med_1valor_Rotulo = new javax.swing.JLabel();
        Med_2valor_Rotulo = new javax.swing.JLabel();
        Med_3valor_Rotulo = new javax.swing.JLabel();
        Med_4valor_Rotulo = new javax.swing.JLabel();
        Med_1valor = new javax.swing.JTextField();
        Med_2valor = new javax.swing.JTextField();
        Med_3valor = new javax.swing.JTextField();
        Med_4valor = new javax.swing.JTextField();
        Med_Res_Rotulo = new javax.swing.JLabel();
        Med_Res = new javax.swing.JLabel();
        Espec_Painel = new javax.swing.JPanel();
        Clear_All = new javax.swing.JButton();
        Close_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        T_Painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabuada:"));

        N_Rotulo.setText("Número:");

        T_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_NumeroActionPerformed(evt);
            }
        });

        T_Calc.setText("Calcular");
        T_Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_CalcActionPerformed(evt);
            }
        });

        T_Clear.setText("Limpar");
        T_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_PainelLayout = new javax.swing.GroupLayout(T_Painel);
        T_Painel.setLayout(T_PainelLayout);
        T_PainelLayout.setHorizontalGroup(
            T_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_PainelLayout.createSequentialGroup()
                .addGroup(T_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_PainelLayout.createSequentialGroup()
                        .addComponent(N_Rotulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(T_Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(T_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T_Calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        T_PainelLayout.setVerticalGroup(
            T_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_PainelLayout.createSequentialGroup()
                .addGroup(T_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(N_Rotulo)
                        .addComponent(T_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(T_Calc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_PainelLayout.createSequentialGroup()
                        .addComponent(T_Clear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(T_PainelLayout.createSequentialGroup()
                        .addComponent(T_Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        G_Painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Graus:"));

        G_Rotulo.setText("Número:");

        G_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_NumeroActionPerformed(evt);
            }
        });

        G_Calc.setText("Calcular:");

        G_Clear.setText("Limpar");

        G_Sen.setText("Seno:");

        G_Cos.setText("Cosseno:");

        G_Sen_Res.setText("0");

        G_Cos_Res.setText("0");

        javax.swing.GroupLayout G_PainelLayout = new javax.swing.GroupLayout(G_Painel);
        G_Painel.setLayout(G_PainelLayout);
        G_PainelLayout.setHorizontalGroup(
            G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(G_PainelLayout.createSequentialGroup()
                        .addComponent(G_Cos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(G_Cos_Res)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(G_PainelLayout.createSequentialGroup()
                        .addGroup(G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G_PainelLayout.createSequentialGroup()
                                .addComponent(G_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(G_PainelLayout.createSequentialGroup()
                                .addComponent(G_Sen)
                                .addGap(23, 23, 23)))
                        .addGroup(G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(G_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G_Sen_Res))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(G_Calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(G_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        G_PainelLayout.setVerticalGroup(
            G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G_Rotulo)
                    .addComponent(G_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G_Calc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G_Clear)
                    .addComponent(G_Sen)
                    .addComponent(G_Sen_Res))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(G_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G_Cos)
                    .addComponent(G_Cos_Res))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fat_Painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Fatorial:"));

        Fat_Rotulo.setText("Número:");

        Fat_Calc.setText("Calcular:");

        Fat_Clear.setText("Limpar");

        Fat_Res_Rotulo.setText("Resultado:");

        Fat_Res.setText("0");

        javax.swing.GroupLayout Fat_PainelLayout = new javax.swing.GroupLayout(Fat_Painel);
        Fat_Painel.setLayout(Fat_PainelLayout);
        Fat_PainelLayout.setHorizontalGroup(
            Fat_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fat_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Fat_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fat_PainelLayout.createSequentialGroup()
                        .addComponent(Fat_Rotulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fat_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Fat_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Fat_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fat_Calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(Fat_PainelLayout.createSequentialGroup()
                        .addComponent(Fat_Res_Rotulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fat_Res)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Fat_PainelLayout.setVerticalGroup(
            Fat_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fat_PainelLayout.createSequentialGroup()
                .addGroup(Fat_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fat_PainelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(Fat_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fat_Rotulo)
                            .addComponent(Fat_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Fat_PainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Fat_Calc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fat_Clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Fat_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fat_Res_Rotulo)
                    .addComponent(Fat_Res))
                .addContainerGap())
        );

        Mult_Painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Múltiplos:"));

        Mult_Rotulo.setText("Número");

        Mult_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mult_NumeroActionPerformed(evt);
            }
        });

        Mult_Calc.setText("Calcular");
        Mult_Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mult_CalcActionPerformed(evt);
            }
        });

        Mult_Clear.setText("Limpar");
        Mult_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mult_ClearActionPerformed(evt);
            }
        });

        Mult_Dobro_Rotulo.setText("Dobro: ");

        Mult_Dobro_Res.setText("0");

        Mult_Triplo_Rotulo.setText("Triplo: ");

        Mult_Triplo_Res.setText("0");

        Mult_Quadruplo_Rotulo.setText("Quádruplo:");

        Mult_Quadruplo_Res.setText("0");

        Mult_Quintuplo_Rotulo.setText("Quintuplo:");

        Mult_Quintuplo_Res.setText("0");

        javax.swing.GroupLayout Mult_PainelLayout = new javax.swing.GroupLayout(Mult_Painel);
        Mult_Painel.setLayout(Mult_PainelLayout);
        Mult_PainelLayout.setHorizontalGroup(
            Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mult_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mult_PainelLayout.createSequentialGroup()
                        .addComponent(Mult_Rotulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mult_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Mult_PainelLayout.createSequentialGroup()
                        .addGroup(Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Mult_PainelLayout.createSequentialGroup()
                                .addComponent(Mult_Dobro_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mult_Dobro_Res))
                            .addGroup(Mult_PainelLayout.createSequentialGroup()
                                .addComponent(Mult_Triplo_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mult_Triplo_Res)))
                        .addGap(44, 44, 44)
                        .addGroup(Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Mult_PainelLayout.createSequentialGroup()
                                .addComponent(Mult_Quadruplo_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mult_Quadruplo_Res))
                            .addGroup(Mult_PainelLayout.createSequentialGroup()
                                .addComponent(Mult_Quintuplo_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mult_Quintuplo_Res)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Mult_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mult_Calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        Mult_PainelLayout.setVerticalGroup(
            Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mult_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mult_Rotulo)
                    .addComponent(Mult_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mult_Calc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mult_Clear)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mult_Dobro_Rotulo)
                        .addComponent(Mult_Dobro_Res)
                        .addComponent(Mult_Quadruplo_Rotulo)
                        .addComponent(Mult_Quadruplo_Res)))
                .addGap(18, 18, 18)
                .addGroup(Mult_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mult_Triplo_Rotulo)
                    .addComponent(Mult_Triplo_Res)
                    .addComponent(Mult_Quintuplo_Rotulo)
                    .addComponent(Mult_Quintuplo_Res))
                .addGap(23, 23, 23))
        );

        Pot_Painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Potencia: "));

        Pot_Rotulo.setText("Número:");

        Pot_Calc.setText("Calcular");
        Pot_Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pot_CalcActionPerformed(evt);
            }
        });

        Pot_Clear.setText("Limpar");
        Pot_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pot_ClearActionPerformed(evt);
            }
        });

        Pot_Qadrado_Rotulo.setText("Quadrado:");

        Pot_Quadrado_Res.setText("0");

        Pot_Cubo_Rotulo.setText("Cubo:");

        Pot_Cubo_Res.setText("0");

        Pot_4pot_Rotulo.setText("4° Potencia:");

        Pot_4pot_Res.setText("0");

        Pot_5pot_Rotulo.setText("5° Potencia:");

        Pot_5pot_Res.setText("0");

        Pot_6pot_Rotulo.setText("6° Potencia:");

        Pot_6pot_Res.setText("0");

        Pot_7pot_Rotulo.setText("7° Potencia:");

        Pot_7pot_Res.setText("0");

        javax.swing.GroupLayout Pot_PainelLayout = new javax.swing.GroupLayout(Pot_Painel);
        Pot_Painel.setLayout(Pot_PainelLayout);
        Pot_PainelLayout.setHorizontalGroup(
            Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pot_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pot_PainelLayout.createSequentialGroup()
                        .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pot_PainelLayout.createSequentialGroup()
                                .addComponent(Pot_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pot_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pot_PainelLayout.createSequentialGroup()
                                .addComponent(Pot_Qadrado_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pot_Quadrado_Res)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pot_PainelLayout.createSequentialGroup()
                                .addComponent(Pot_6pot_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pot_6pot_Res))
                            .addGroup(Pot_PainelLayout.createSequentialGroup()
                                .addComponent(Pot_5pot_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pot_5pot_Res))
                            .addGroup(Pot_PainelLayout.createSequentialGroup()
                                .addComponent(Pot_7pot_Rotulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pot_7pot_Res)))
                        .addGap(10, 10, 10)
                        .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Pot_Calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pot_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Pot_PainelLayout.createSequentialGroup()
                        .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pot_4pot_Rotulo)
                            .addComponent(Pot_Cubo_Rotulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pot_Cubo_Res)
                            .addComponent(Pot_4pot_Res))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Pot_PainelLayout.setVerticalGroup(
            Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pot_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pot_Rotulo)
                    .addComponent(Pot_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pot_Calc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pot_Clear)
                    .addComponent(Pot_Qadrado_Rotulo)
                    .addComponent(Pot_5pot_Rotulo)
                    .addComponent(Pot_5pot_Res)
                    .addComponent(Pot_Quadrado_Res))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pot_Cubo_Rotulo)
                    .addComponent(Pot_Cubo_Res)
                    .addComponent(Pot_6pot_Rotulo)
                    .addComponent(Pot_6pot_Res))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pot_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pot_4pot_Rotulo)
                    .addComponent(Pot_4pot_Res)
                    .addComponent(Pot_7pot_Rotulo)
                    .addComponent(Pot_7pot_Res))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Med_Painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Média Aritimética"));

        Med_Calc.setText("Calcular");
        Med_Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Med_CalcActionPerformed(evt);
            }
        });

        Med_Clear.setText("Limpar");
        Med_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Med_ClearActionPerformed(evt);
            }
        });

        Med_1valor_Rotulo.setText("1° Valor:");

        Med_2valor_Rotulo.setText("2° Valor:");

        Med_3valor_Rotulo.setText("3° Valor:");

        Med_4valor_Rotulo.setText("4° Valor:");

        Med_Res_Rotulo.setText("Média:");

        Med_Res.setText("0");

        javax.swing.GroupLayout Med_PainelLayout = new javax.swing.GroupLayout(Med_Painel);
        Med_Painel.setLayout(Med_PainelLayout);
        Med_PainelLayout.setHorizontalGroup(
            Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Med_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Med_2valor_Rotulo)
                    .addComponent(Med_1valor_Rotulo)
                    .addComponent(Med_3valor_Rotulo)
                    .addComponent(Med_4valor_Rotulo))
                .addGap(18, 18, 18)
                .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Med_4valor)
                    .addComponent(Med_3valor)
                    .addComponent(Med_1valor)
                    .addComponent(Med_2valor))
                .addGap(98, 98, 98)
                .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Med_Calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Med_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(Med_PainelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(Med_Res_Rotulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Med_Res)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Med_PainelLayout.setVerticalGroup(
            Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Med_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Med_Calc)
                        .addComponent(Med_1valor_Rotulo, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(Med_1valor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Med_Clear)
                    .addGroup(Med_PainelLayout.createSequentialGroup()
                        .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Med_2valor_Rotulo)
                            .addComponent(Med_2valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Med_3valor_Rotulo)
                            .addComponent(Med_3valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Med_4valor_Rotulo)
                    .addComponent(Med_4valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Med_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Med_Res_Rotulo)
                    .addComponent(Med_Res))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Espec_Painel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Clear_All.setText("Limpar Todos");
        Clear_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_AllActionPerformed(evt);
            }
        });

        Close_Button.setText("Fechar Formulário");
        Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Espec_PainelLayout = new javax.swing.GroupLayout(Espec_Painel);
        Espec_Painel.setLayout(Espec_PainelLayout);
        Espec_PainelLayout.setHorizontalGroup(
            Espec_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Espec_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Clear_All, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Close_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        Espec_PainelLayout.setVerticalGroup(
            Espec_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Espec_PainelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Espec_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear_All)
                    .addComponent(Close_Button))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(T_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(G_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Fat_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mult_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pot_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Med_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Espec_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Med_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Espec_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(T_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fat_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mult_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(G_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Pot_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T_CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_CalcActionPerformed
        int T_n = Integer.parseInt(T_Numero.getText());
        //int tabuada = 0;
        for (int contador = 1; contador <= 10; contador++){
            int tabuada = T_n * contador;
            Integer.toString(T_n);
            Integer.toString(contador);
            Integer.toString(tabuada);
            T_Resultado.add(T_n + " x " + contador + " = " + tabuada);
        }
    }//GEN-LAST:event_T_CalcActionPerformed

    private void T_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_ClearActionPerformed
        T_Resultado.removeAll();
        T_Numero.setText("");
        T_Numero.requestFocus();
    }//GEN-LAST:event_T_ClearActionPerformed

    private void T_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_NumeroActionPerformed
        //int T_n = integer.paeseint(T_Numero.getText());
    }//GEN-LAST:event_T_NumeroActionPerformed

    private void G_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_NumeroActionPerformed

    private void Mult_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mult_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mult_NumeroActionPerformed

    private void Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_ButtonActionPerformed
        dispose();
    }//GEN-LAST:event_Close_ButtonActionPerformed

    private void Pot_CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pot_CalcActionPerformed
        double base = Double.parseDouble(Pot_Numero.getText());
        double quadrado = Math.pow(base, 2);
        double cubo = Math.pow(base, 3);
        double quarta = Math.pow(base, 4);
        double quinta = Math.pow(base, 5);
        double sexta = Math.pow(base, 6);
        double setima = Math.pow(base, 7);
        Pot_Quadrado_Res.setText(Double.toString(quadrado));
        Pot_Cubo_Res.setText(Double.toString(cubo));
        Pot_4pot_Res.setText(Double.toString(quarta));
        Pot_5pot_Res.setText(Double.toString(quinta));
        Pot_6pot_Res.setText(Double.toString(sexta));
        Pot_7pot_Res.setText(Double.toString(setima));
    }//GEN-LAST:event_Pot_CalcActionPerformed

    private void Pot_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pot_ClearActionPerformed
        Pot_Quadrado_Res.setText("0");
        Pot_Cubo_Res.setText("0");
        Pot_4pot_Res.setText("0");
        Pot_5pot_Res.setText("0");
        Pot_6pot_Res.setText("0");
        Pot_7pot_Res.setText("0");
        Pot_Numero.setText("");
        Pot_Numero.requestFocus(true);
    }//GEN-LAST:event_Pot_ClearActionPerformed

    private void Mult_CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mult_CalcActionPerformed
        double n = Double.parseDouble(Mult_Numero.getText());
        double duplo = n*2;
        double triplo = n*3;
        double quadr = n*4;
        double quint = n*5;
        Mult_Dobro_Res.setText(Double.toString(duplo));
        Mult_Triplo_Res.setText(Double.toString(triplo));
        Mult_Quadruplo_Res.setText(Double.toString(quadr));
        Mult_Quintuplo_Res.setText(Double.toString(quint));
    }//GEN-LAST:event_Mult_CalcActionPerformed

    private void Mult_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mult_ClearActionPerformed
        Mult_Dobro_Res.setText("0");
        Mult_Triplo_Res.setText("0");
        Mult_Quadruplo_Res.setText("0");
        Mult_Quintuplo_Res.setText("0");
        Mult_Numero.setText("");
        Mult_Numero.requestFocus(true);
    }//GEN-LAST:event_Mult_ClearActionPerformed

    private void Med_CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Med_CalcActionPerformed
        double MedR = (Double.parseDouble(Med_1valor.getText())+
            Double.parseDouble(Med_2valor.getText())+
            Double.parseDouble(Med_3valor.getText())+
            Double.parseDouble(Med_4valor.getText()))/4;
        Med_Res.setText(Double.toString(MedR));
    }//GEN-LAST:event_Med_CalcActionPerformed

    private void Med_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Med_ClearActionPerformed
        Med_1valor.setText("");
        Med_2valor.setText("");
        Med_3valor.setText("");
        Med_4valor.setText("");
        Med_Res.setText("0");
        Med_1valor.requestFocus(true);
    }//GEN-LAST:event_Med_ClearActionPerformed

    private void Clear_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_AllActionPerformed
        Med_1valor.setText("");
        Med_2valor.setText("");
        Med_3valor.setText("");
        Med_4valor.setText("");
        Med_Res.setText("0");
        Mult_Dobro_Res.setText("0");
        Mult_Triplo_Res.setText("0");
        Mult_Quadruplo_Res.setText("0");
        Mult_Quintuplo_Res.setText("0");
        Mult_Numero.setText("");
        Pot_Quadrado_Res.setText("0");
        Pot_Cubo_Res.setText("0");
        Pot_4pot_Res.setText("0");
        Pot_5pot_Res.setText("0");
        Pot_6pot_Res.setText("0");
        Pot_7pot_Res.setText("0");
        Pot_Numero.setText("");
        T_Resultado.removeAll();
        T_Numero.setText("");
        T_Numero.requestFocus();
    }//GEN-LAST:event_Clear_AllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Calc_Mat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Calc_Mat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Calc_Mat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Calc_Mat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Calc_Mat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_All;
    private javax.swing.JButton Close_Button;
    private javax.swing.JPanel Espec_Painel;
    private javax.swing.JButton Fat_Calc;
    private javax.swing.JButton Fat_Clear;
    private javax.swing.JTextField Fat_Numero;
    private javax.swing.JPanel Fat_Painel;
    private javax.swing.JLabel Fat_Res;
    private javax.swing.JLabel Fat_Res_Rotulo;
    private javax.swing.JLabel Fat_Rotulo;
    private javax.swing.JButton G_Calc;
    private javax.swing.JButton G_Clear;
    private javax.swing.JLabel G_Cos;
    private javax.swing.JLabel G_Cos_Res;
    private javax.swing.JTextField G_Numero;
    private javax.swing.JPanel G_Painel;
    private javax.swing.JLabel G_Rotulo;
    private javax.swing.JLabel G_Sen;
    private javax.swing.JLabel G_Sen_Res;
    private javax.swing.JTextField Med_1valor;
    private javax.swing.JLabel Med_1valor_Rotulo;
    private javax.swing.JTextField Med_2valor;
    private javax.swing.JLabel Med_2valor_Rotulo;
    private javax.swing.JTextField Med_3valor;
    private javax.swing.JLabel Med_3valor_Rotulo;
    private javax.swing.JTextField Med_4valor;
    private javax.swing.JLabel Med_4valor_Rotulo;
    private javax.swing.JButton Med_Calc;
    private javax.swing.JButton Med_Clear;
    private javax.swing.JPanel Med_Painel;
    private javax.swing.JLabel Med_Res;
    private javax.swing.JLabel Med_Res_Rotulo;
    private javax.swing.JButton Mult_Calc;
    private javax.swing.JButton Mult_Clear;
    private javax.swing.JLabel Mult_Dobro_Res;
    private javax.swing.JLabel Mult_Dobro_Rotulo;
    private javax.swing.JTextField Mult_Numero;
    private javax.swing.JPanel Mult_Painel;
    private javax.swing.JLabel Mult_Quadruplo_Res;
    private javax.swing.JLabel Mult_Quadruplo_Rotulo;
    private javax.swing.JLabel Mult_Quintuplo_Res;
    private javax.swing.JLabel Mult_Quintuplo_Rotulo;
    private javax.swing.JLabel Mult_Rotulo;
    private javax.swing.JLabel Mult_Triplo_Res;
    private javax.swing.JLabel Mult_Triplo_Rotulo;
    private javax.swing.JLabel N_Rotulo;
    private javax.swing.JLabel Pot_4pot_Res;
    private javax.swing.JLabel Pot_4pot_Rotulo;
    private javax.swing.JLabel Pot_5pot_Res;
    private javax.swing.JLabel Pot_5pot_Rotulo;
    private javax.swing.JLabel Pot_6pot_Res;
    private javax.swing.JLabel Pot_6pot_Rotulo;
    private javax.swing.JLabel Pot_7pot_Res;
    private javax.swing.JLabel Pot_7pot_Rotulo;
    private javax.swing.JButton Pot_Calc;
    private javax.swing.JButton Pot_Clear;
    private javax.swing.JLabel Pot_Cubo_Res;
    private javax.swing.JLabel Pot_Cubo_Rotulo;
    private javax.swing.JTextField Pot_Numero;
    private javax.swing.JPanel Pot_Painel;
    private javax.swing.JLabel Pot_Qadrado_Rotulo;
    private javax.swing.JLabel Pot_Quadrado_Res;
    private javax.swing.JLabel Pot_Rotulo;
    private javax.swing.JButton T_Calc;
    private javax.swing.JButton T_Clear;
    private javax.swing.JTextField T_Numero;
    private javax.swing.JPanel T_Painel;
    private java.awt.List T_Resultado;
    // End of variables declaration//GEN-END:variables
}
