/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejava;

/**
 *
 * @author Rafael Assis
 */
import javax.swing.JOptionPane;

public class Frm_Tela_Inicial extends javax.swing.JFrame {
    /**
     * Creates new form Frm_Tela_Inicial
     */
    public Frm_Tela_Inicial() {
        initComponents();
        Option_Mat.setSelected(true);
        Option_Mat.requestFocus(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Selection = new javax.swing.ButtonGroup();
        Inicial_Painel = new javax.swing.JPanel();
        Option_Mat = new javax.swing.JRadioButton();
        Option_Financ = new javax.swing.JRadioButton();
        Option_Espec = new javax.swing.JRadioButton();
        Avancar = new javax.swing.JButton();
        Button_Quit = new javax.swing.JButton();
        About_Button = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cálculo Java");

        Inicial_Painel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Selection.add(Option_Mat);
        Option_Mat.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 11)); // NOI18N
        Option_Mat.setText("Cálculos Matemáticos");
        Option_Mat.setToolTipText("");
        Option_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option_MatActionPerformed(evt);
            }
        });

        Selection.add(Option_Financ);
        Option_Financ.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 11)); // NOI18N
        Option_Financ.setText("Cálculos fianceiros");
        Option_Financ.setToolTipText("");

        Selection.add(Option_Espec);
        Option_Espec.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 11)); // NOI18N
        Option_Espec.setText("Cálculos Especiais");
        Option_Espec.setToolTipText("");

        Avancar.setText("Avançar");
        Avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvancarActionPerformed(evt);
            }
        });

        Button_Quit.setText("Sair");
        Button_Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_QuitActionPerformed(evt);
            }
        });

        About_Button.setText("Sobre");
        About_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inicial_PainelLayout = new javax.swing.GroupLayout(Inicial_Painel);
        Inicial_Painel.setLayout(Inicial_PainelLayout);
        Inicial_PainelLayout.setHorizontalGroup(
            Inicial_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicial_PainelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(Inicial_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Inicial_PainelLayout.createSequentialGroup()
                        .addGroup(Inicial_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Option_Espec)
                            .addComponent(Option_Financ)
                            .addComponent(Option_Mat))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Inicial_PainelLayout.createSequentialGroup()
                        .addComponent(Avancar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(Button_Quit)
                        .addGap(81, 81, 81))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inicial_PainelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(About_Button)
                .addContainerGap())
        );
        Inicial_PainelLayout.setVerticalGroup(
            Inicial_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicial_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(About_Button)
                .addGap(2, 2, 2)
                .addComponent(Option_Mat)
                .addGap(18, 18, 18)
                .addComponent(Option_Financ)
                .addGap(18, 18, 18)
                .addComponent(Option_Espec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(Inicial_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Avancar)
                    .addComponent(Button_Quit))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicial_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicial_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Option_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option_MatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option_MatActionPerformed

    private void Button_QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_QuitActionPerformed
      int confirma = JOptionPane.showConfirmDialog(this,"Deseja sair do sistema?","Sair",JOptionPane.YES_NO_OPTION);
      if(confirma == 0){
          System.exit(0);
      }
    }//GEN-LAST:event_Button_QuitActionPerformed

    private void AvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvancarActionPerformed
        if(Option_Mat.isSelected()) {
            new Frm_Calc_Mat().setVisible(true);
        }
        if(Option_Financ.isSelected()){
            new Frm_Calc_Financ().setVisible(true);
        }
        if (Option_Espec.isSelected()) {
            new Frm_Calc_Espec().setVisible(true);
        }
    }//GEN-LAST:event_AvancarActionPerformed

    private void About_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_ButtonActionPerformed
        new Frm_About().setVisible(true);
    }//GEN-LAST:event_About_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Tela_Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_Button;
    private javax.swing.JButton Avancar;
    private javax.swing.JButton Button_Quit;
    private javax.swing.JPanel Inicial_Painel;
    private javax.swing.JRadioButton Option_Espec;
    private javax.swing.JRadioButton Option_Financ;
    private javax.swing.JRadioButton Option_Mat;
    private javax.swing.ButtonGroup Selection;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
