/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejava;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;

/**
 *
 * @author  Rafael Assis
 */ 
public class Frm_Calc_Financ extends javax.swing.JFrame {

    DecimalFormat decimal = new DecimalFormat("#0.00");
    public void calctotal() {
       double quantiaRegata = Double.parseDouble(Regata_Quant.getText()) * 19.90;
       double quantiaSocial = Double.parseDouble(Social_Quant.getText()) * 59.90;
       double quantiaBlusa = Double.parseDouble(Blusa_Quant.getText()) * 119.90;
       double quantiaPullover = Double.parseDouble(Pullover_Quant.getText()) * 39.90;
       double quantiaSapato = Double.parseDouble(Sapato_Quant.getText()) * 99.90;
       double quantiaCalca = Double.parseDouble(Calca_Quant.getText()) * 38.90;
       double quantiaMeia = Double.parseDouble(Meia_Quant.getText()) * 9.90;
       double quantiaLuva = Double.parseDouble(Luva_Quant.getText()) * 24.90;
       double quantiaJaq = Double.parseDouble(Jaq_Quant.getText()) * 329.90;
       double quantiaBerm = Double.parseDouble(Berm_Quant.getText()) * 69.90;
       double quantiaChinelo = Double.parseDouble(Chinelo_Quant.getText()) * 14.90;
       double quantiaBone = Double.parseDouble(Bone_Quant.getText()) * 6.90;
       Tot_Regata.setText(decimal.format(quantiaRegata));
       Tot_Social.setText(decimal.format(quantiaSocial));
       Tot_Blusa.setText(decimal.format(quantiaBlusa));
       Tot_Pullover.setText(decimal.format(quantiaPullover));
       Tot_Sapato.setText(decimal.format(quantiaSapato));
       Tot_Calca.setText(decimal.format(quantiaCalca));
       Tot_Meia.setText(decimal.format(quantiaMeia));
       Tot_Luva.setText(decimal.format(quantiaLuva));
       Tot_Jaq.setText(decimal.format(quantiaJaq));
       Tot_Berm.setText(decimal.format(quantiaBerm));
       Tot_Chinelo.setText(decimal.format(quantiaChinelo));
       Tot_Bone.setText(decimal.format(quantiaBone));
       SubTotal = quantiaRegata + quantiaSocial + quantiaBlusa + quantiaPullover + quantiaSapato + quantiaCalca + quantiaMeia + quantiaLuva + quantiaJaq + quantiaBerm + quantiaChinelo + quantiaBone;
       Sub_Total.setText(decimal.format(SubTotal));
}
    double SubTotal;
    public void formaPag(){
           if(RB_Praz.isSelected() == true){
            Parc_Quant.setEnabled(true);
        }
        else{
            Parc_Quant.setEnabled(false);
        }
    }
    /**
     * Creates new form Frm_Calc_Financ
     */
    public Frm_Calc_Financ() {
        initComponents();
        RB_Vis.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RB_Formas = new javax.swing.ButtonGroup();
        Financ_Painel = new javax.swing.JPanel();
        Product_Label = new javax.swing.JLabel();
        Preco_Label = new javax.swing.JLabel();
        Blusa_Preco = new javax.swing.JLabel();
        Pullover_Preço = new javax.swing.JLabel();
        Regata_Preco = new javax.swing.JLabel();
        Social_Preco = new javax.swing.JLabel();
        Sapato_Preco = new javax.swing.JLabel();
        Calca_Preco = new javax.swing.JLabel();
        Luva_Preco = new javax.swing.JLabel();
        Meia_Preco = new javax.swing.JLabel();
        Jaq_Preco = new javax.swing.JLabel();
        Berm_Preco = new javax.swing.JLabel();
        Chinelo_Preco = new javax.swing.JLabel();
        Bone_Preco = new javax.swing.JLabel();
        Quant_Label = new javax.swing.JLabel();
        Blusa_Quant = new javax.swing.JTextField();
        Pullover_Quant = new javax.swing.JTextField();
        Regata_Quant = new javax.swing.JTextField();
        Social_Quant = new javax.swing.JTextField();
        Sapato_Quant = new javax.swing.JTextField();
        Calca_Quant = new javax.swing.JTextField();
        Meia_Quant = new javax.swing.JTextField();
        Luva_Quant = new javax.swing.JTextField();
        Jaq_Quant = new javax.swing.JTextField();
        Berm_Quant = new javax.swing.JTextField();
        Chinelo_Quant = new javax.swing.JTextField();
        Total_Label = new javax.swing.JLabel();
        Tot_Regata = new javax.swing.JLabel();
        Tot_Social = new javax.swing.JLabel();
        Tot_Blusa = new javax.swing.JLabel();
        Tot_Pullover = new javax.swing.JLabel();
        Tot_Sapato = new javax.swing.JLabel();
        Tot_Calca = new javax.swing.JLabel();
        Tot_Meia = new javax.swing.JLabel();
        Tot_Luva = new javax.swing.JLabel();
        Tot_Jaq = new javax.swing.JLabel();
        Tot_Berm = new javax.swing.JLabel();
        Tot_Chinelo = new javax.swing.JLabel();
        Bone_Quant = new javax.swing.JTextField();
        Tot_Bone = new javax.swing.JLabel();
        Regata_Check = new javax.swing.JCheckBox();
        Social_Check = new javax.swing.JCheckBox();
        Blusa_Check = new javax.swing.JCheckBox();
        Pullover_Check = new javax.swing.JCheckBox();
        Berm_Check = new javax.swing.JCheckBox();
        Jaq_Check = new javax.swing.JCheckBox();
        Chinelo_Check = new javax.swing.JCheckBox();
        Bone_Check = new javax.swing.JCheckBox();
        Sapato_Check = new javax.swing.JCheckBox();
        Calca_Check = new javax.swing.JCheckBox();
        Meia_Check = new javax.swing.JCheckBox();
        Luva_Check = new javax.swing.JCheckBox();
        Sub_Label = new javax.swing.JLabel();
        Sub_Total = new javax.swing.JLabel();
        Sub_Button = new javax.swing.JButton();
        For_Pag = new javax.swing.JPanel();
        RB_Vis = new javax.swing.JRadioButton();
        RB_Praz = new javax.swing.JRadioButton();
        Qt_Parc_Label = new javax.swing.JLabel();
        Parc_Quant = new javax.swing.JComboBox();
        Tot_Parc_label = new javax.swing.JLabel();
        Tot_Parc = new javax.swing.JLabel();
        Desc_Label = new javax.swing.JLabel();
        Desc = new javax.swing.JLabel();
        Total_Financ_Lable = new javax.swing.JLabel();
        Total_Pag = new javax.swing.JLabel();
        Calc_Total = new javax.swing.JButton();
        Clear_All = new javax.swing.JButton();
        Quit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Financ_Painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de vendas:"));

        Product_Label.setText("Produtos:");

        Preco_Label.setText("Preço (em R$):");

        Blusa_Preco.setText("119,90");

        Pullover_Preço.setText("39,90");

        Regata_Preco.setText("19,90");

        Social_Preco.setText("59,90");

        Sapato_Preco.setText("99.90");

        Calca_Preco.setText("38.90");

        Luva_Preco.setText("24,90");

        Meia_Preco.setText("9,90");

        Jaq_Preco.setText("329.90");

        Berm_Preco.setText("69.90");

        Chinelo_Preco.setText("14.90");

        Bone_Preco.setText("6.90");

        Quant_Label.setText("Quantidade:");

        Blusa_Quant.setEditable(false);
        Blusa_Quant.setText("0");
        Blusa_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Pullover_Quant.setEditable(false);
        Pullover_Quant.setText("0");
        Pullover_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Regata_Quant.setEditable(false);
        Regata_Quant.setText("0");
        Regata_Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regata_QuantActionPerformed(evt);
            }
        });
        Regata_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Social_Quant.setEditable(false);
        Social_Quant.setText("0");
        Social_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Sapato_Quant.setEditable(false);
        Sapato_Quant.setText("0");
        Sapato_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Calca_Quant.setEditable(false);
        Calca_Quant.setText("0");
        Calca_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Meia_Quant.setEditable(false);
        Meia_Quant.setText("0");
        Meia_Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meia_QuantActionPerformed(evt);
            }
        });
        Meia_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Luva_Quant.setEditable(false);
        Luva_Quant.setText("0");
        Luva_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Jaq_Quant.setEditable(false);
        Jaq_Quant.setText("0");
        Jaq_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Berm_Quant.setEditable(false);
        Berm_Quant.setText("0");
        Berm_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Chinelo_Quant.setEditable(false);
        Chinelo_Quant.setText("0");
        Chinelo_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Total_Label.setText("Total R$:");

        Tot_Regata.setText("0.00");

        Tot_Social.setText("0.00");

        Tot_Blusa.setText("0.00");

        Tot_Pullover.setText("0.00");

        Tot_Sapato.setText("0.00");

        Tot_Calca.setText("0.00");

        Tot_Meia.setText("0.00");

        Tot_Luva.setText("0.00");

        Tot_Jaq.setText("0.00");

        Tot_Berm.setText("0.00");

        Tot_Chinelo.setText("0.00");

        Bone_Quant.setEditable(false);
        Bone_Quant.setText("0");
        Bone_Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bone_QuantActionPerformed(evt);
            }
        });
        Bone_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caracteres(evt);
            }
        });

        Tot_Bone.setText("0.00");

        Regata_Check.setText("Camiseta Regata");
        Regata_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regata_CheckActionPerformed(evt);
            }
        });

        Social_Check.setText("Camisa Social");
        Social_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Social_CheckActionPerformed(evt);
            }
        });

        Blusa_Check.setText("Blusa");
        Blusa_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blusa_CheckActionPerformed(evt);
            }
        });

        Pullover_Check.setText("Pullover");
        Pullover_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pullover_CheckActionPerformed(evt);
            }
        });

        Berm_Check.setText("Bermuda");
        Berm_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Berm_CheckActionPerformed(evt);
            }
        });

        Jaq_Check.setText("Jaqueta");
        Jaq_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jaq_CheckActionPerformed(evt);
            }
        });

        Chinelo_Check.setText("Chinelo");
        Chinelo_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chinelo_CheckActionPerformed(evt);
            }
        });

        Bone_Check.setText("Boné");
        Bone_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bone_CheckActionPerformed(evt);
            }
        });

        Sapato_Check.setText("Sapato");
        Sapato_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sapato_CheckActionPerformed(evt);
            }
        });

        Calca_Check.setText("Calça");
        Calca_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calca_CheckActionPerformed(evt);
            }
        });

        Meia_Check.setText("Meias");
        Meia_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meia_CheckActionPerformed(evt);
            }
        });

        Luva_Check.setText("Luva");
        Luva_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Luva_CheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Financ_PainelLayout = new javax.swing.GroupLayout(Financ_Painel);
        Financ_Painel.setLayout(Financ_PainelLayout);
        Financ_PainelLayout.setHorizontalGroup(
            Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Financ_PainelLayout.createSequentialGroup()
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Product_Label)
                    .addGroup(Financ_PainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Regata_Check)
                            .addComponent(Social_Check)
                            .addComponent(Blusa_Check)
                            .addComponent(Pullover_Check)
                            .addComponent(Jaq_Check)
                            .addComponent(Berm_Check)
                            .addComponent(Chinelo_Check)
                            .addComponent(Bone_Check)
                            .addComponent(Sapato_Check)
                            .addComponent(Calca_Check)
                            .addComponent(Meia_Check)
                            .addComponent(Luva_Check))))
                .addGap(104, 104, 104)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Financ_PainelLayout.createSequentialGroup()
                        .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Blusa_Preco)
                            .addComponent(Calca_Preco)
                            .addComponent(Meia_Preco)
                            .addComponent(Luva_Preco)
                            .addComponent(Jaq_Preco)
                            .addComponent(Berm_Preco)
                            .addComponent(Chinelo_Preco)
                            .addComponent(Bone_Preco)
                            .addComponent(Sapato_Preco))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Financ_PainelLayout.createSequentialGroup()
                        .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Preco_Label)
                            .addComponent(Social_Preco)
                            .addComponent(Pullover_Preço)
                            .addComponent(Regata_Preco)
                            .addGroup(Financ_PainelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Financ_PainelLayout.createSequentialGroup()
                                        .addGap(250, 250, 250)
                                        .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Jaq_Quant)
                                            .addComponent(Quant_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Regata_Quant)
                                            .addComponent(Social_Quant)
                                            .addComponent(Sapato_Quant, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Blusa_Quant, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Pullover_Quant)
                                            .addComponent(Calca_Quant, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Meia_Quant, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Luva_Quant)
                                            .addComponent(Berm_Quant)))
                                    .addComponent(Chinelo_Quant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bone_Quant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Total_Label)
                                    .addComponent(Tot_Bone, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(Tot_Chinelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Berm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Jaq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Luva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Meia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Calca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Sapato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Pullover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Blusa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Social, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tot_Regata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Financ_PainelLayout.setVerticalGroup(
            Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Financ_PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Preco_Label)
                        .addComponent(Product_Label))
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Quant_Label)
                        .addComponent(Total_Label)))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Regata_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tot_Regata))
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Regata_Preco)
                        .addComponent(Regata_Check)))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Social_Preco)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Social_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tot_Social))
                    .addComponent(Social_Check))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Blusa_Preco)
                    .addComponent(Blusa_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tot_Blusa)
                    .addComponent(Blusa_Check))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Pullover_Preço)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pullover_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tot_Pullover)))
                    .addComponent(Pullover_Check))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tot_Sapato)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Sapato_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Sapato_Preco)
                        .addComponent(Sapato_Check)))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calca_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calca_Preco)
                    .addComponent(Tot_Calca)
                    .addComponent(Calca_Check))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tot_Meia)
                        .addComponent(Meia_Preco)
                        .addComponent(Meia_Check))
                    .addComponent(Meia_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Luva_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tot_Luva))
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Luva_Preco)
                        .addComponent(Luva_Check)))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jaq_Preco)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tot_Jaq)
                        .addComponent(Jaq_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jaq_Check))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Berm_Preco)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tot_Berm)
                        .addComponent(Berm_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Berm_Check))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chinelo_Preco)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Chinelo_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tot_Chinelo))
                    .addComponent(Chinelo_Check))
                .addGap(18, 18, 18)
                .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Financ_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bone_Preco)
                        .addComponent(Bone_Check))
                    .addComponent(Bone_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tot_Bone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Sub_Label.setText("Sub-Total: R$");

        Sub_Total.setText("0,00");

        Sub_Button.setText("Sub-Total");
        Sub_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_ButtonActionPerformed(evt);
            }
        });

        For_Pag.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de Pagamento:"));

        RB_Formas.add(RB_Vis);
        RB_Vis.setText("À Vista");
        RB_Vis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_VisActionPerformed(evt);
            }
        });

        RB_Formas.add(RB_Praz);
        RB_Praz.setText("À Prazo");
        RB_Praz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_PrazActionPerformed(evt);
            }
        });

        Qt_Parc_Label.setText("Quantidade de Parcelas: ");

        Parc_Quant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        Parc_Quant.setEnabled(false);
        Parc_Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parc_QuantActionPerformed(evt);
            }
        });

        Tot_Parc_label.setText("Total parcelado: R$");

        Tot_Parc.setText("0.00");

        javax.swing.GroupLayout For_PagLayout = new javax.swing.GroupLayout(For_Pag);
        For_Pag.setLayout(For_PagLayout);
        For_PagLayout.setHorizontalGroup(
            For_PagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(For_PagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(For_PagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(For_PagLayout.createSequentialGroup()
                        .addComponent(Tot_Parc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tot_Parc, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(For_PagLayout.createSequentialGroup()
                        .addGroup(For_PagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB_Vis)
                            .addComponent(RB_Praz)
                            .addGroup(For_PagLayout.createSequentialGroup()
                                .addComponent(Qt_Parc_Label)
                                .addGap(88, 88, 88)
                                .addComponent(Parc_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(99, 99, 99))
        );
        For_PagLayout.setVerticalGroup(
            For_PagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(For_PagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB_Vis)
                .addGap(18, 18, 18)
                .addComponent(RB_Praz)
                .addGap(18, 18, 18)
                .addGroup(For_PagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Qt_Parc_Label)
                    .addComponent(Parc_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(For_PagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tot_Parc_label)
                    .addComponent(Tot_Parc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Desc_Label.setText("Total de Desconto: R$");

        Desc.setText("0.00");

        Total_Financ_Lable.setText("Total a Pagar: R$");

        Total_Pag.setText("0.00");

        Calc_Total.setText("Calcular Total");
        Calc_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_TotalActionPerformed(evt);
            }
        });

        Clear_All.setText("Limpar Tudo");
        Clear_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_AllActionPerformed(evt);
            }
        });

        Quit_Button.setText("Fechar Formulário");
        Quit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(Sub_Button)
                .addGap(87, 87, 87)
                .addComponent(Sub_Label)
                .addGap(29, 29, 29)
                .addComponent(Sub_Total)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Financ_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(For_Pag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Desc_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Total_Financ_Lable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Total_Pag, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Calc_Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Clear_All)
                                .addGap(49, 49, 49))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Quit_Button)
                        .addGap(159, 159, 159))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Financ_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(For_Pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Desc_Label)
                            .addComponent(Desc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total_Financ_Lable)
                            .addComponent(Total_Pag))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Calc_Total)
                            .addComponent(Clear_All))
                        .addGap(18, 18, 18)
                        .addComponent(Quit_Button)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub_Button)
                    .addComponent(Sub_Label)
                    .addComponent(Sub_Total))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Regata_QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regata_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Regata_QuantActionPerformed

    private void Bone_QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bone_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bone_QuantActionPerformed

    private void Parc_QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parc_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Parc_QuantActionPerformed

    private void Quit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quit_ButtonActionPerformed
        dispose();
    }//GEN-LAST:event_Quit_ButtonActionPerformed

    private void caracteres(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caracteres
       String caracter = "0987654321";
       if(!caracter.contains(evt.getKeyChar()+"")){
           evt.consume();
       }
    }//GEN-LAST:event_caracteres

    private void Sub_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_ButtonActionPerformed
       calctotal();
       if(SubTotal == 0){
           JOptionPane.showMessageDialog(this,"O valor do Sub-total não pode ser de R$0.00");
       }
    }//GEN-LAST:event_Sub_ButtonActionPerformed

    private void Regata_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regata_CheckActionPerformed
        if(Regata_Check.isSelected() == true){
            //Regata_Quant.setText("");
            Regata_Quant.setEditable(true);
            Regata_Quant.requestFocus(true);
        }
        else{
            Regata_Quant.setText("0");
            Regata_Quant.setEditable(false);
        }
    }//GEN-LAST:event_Regata_CheckActionPerformed

    private void Social_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Social_CheckActionPerformed
        if(Social_Check.isSelected() == true){
            //Social_Quant.setText("");
            Social_Quant.setEditable(true);
            Social_Quant.requestFocus(true);
        }
        else{
            Social_Quant.setEditable(false);
            Social_Quant.setText("0");
        }
    }//GEN-LAST:event_Social_CheckActionPerformed

    private void Blusa_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blusa_CheckActionPerformed
        if(Blusa_Check.isSelected() == true){
            //Blusa_Quant.setText("");
            Blusa_Quant.setEditable(true);
            Blusa_Quant.requestFocus(true);
        }
        else{
            Blusa_Quant.setEditable(false);
            Blusa_Quant.setText("0");
        }
    }//GEN-LAST:event_Blusa_CheckActionPerformed

    private void Pullover_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pullover_CheckActionPerformed
        if(Pullover_Check.isSelected() == true){
            //Pullover_Quant.setText("");
            Pullover_Quant.setEditable(true);
            Pullover_Quant.requestFocus(true);
        }
        else{
            Pullover_Quant.setEditable(false);
            Pullover_Quant.setText("0");
        }
    }//GEN-LAST:event_Pullover_CheckActionPerformed

    private void Sapato_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sapato_CheckActionPerformed
        if(Sapato_Check.isSelected() == true){
            //Sapato_Quant.setText("");
            Sapato_Quant.setEditable(true);
            Sapato_Quant.requestFocus(true);
        }
        else{
            Sapato_Quant.setEditable(false);
            Sapato_Quant.setText("0");
        }
    }//GEN-LAST:event_Sapato_CheckActionPerformed

    private void Calca_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calca_CheckActionPerformed
        if(Calca_Check.isSelected() == true){
            //Calca_Quant.setText("");
            Calca_Quant.setEditable(true);
            Calca_Quant.requestFocus(true);
        }
        else{
            Calca_Quant.setEditable(false);
            Calca_Quant.setText("0");
        }
    }//GEN-LAST:event_Calca_CheckActionPerformed

    private void Meia_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meia_CheckActionPerformed
        if(Meia_Check.isSelected() == true){
            //Meia_Quant.setText("");
            Meia_Quant.setEditable(true);
            Meia_Quant.requestFocus(true);
        }
        else{
            Meia_Quant.setEditable(false);
            Meia_Quant.setText("0");
        }
    }//GEN-LAST:event_Meia_CheckActionPerformed

    private void Luva_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Luva_CheckActionPerformed
        if(Luva_Check.isSelected() == true){
            //Luva_Quant.setText("");
            Luva_Quant.setEditable(true);
            Luva_Quant.requestFocus(true);
        }
        else{
            Luva_Quant.setEditable(false);
            Luva_Quant.setText("0");
        }
    }//GEN-LAST:event_Luva_CheckActionPerformed

    private void Jaq_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jaq_CheckActionPerformed
        if(Jaq_Check.isSelected() == true){
            //Jaq_Quant.setText("");
            Jaq_Quant.setEditable(true);
            Jaq_Quant.requestFocus(true);
        }
        else{
            Jaq_Quant.setEditable(false);
            Jaq_Quant.setText("0");
        }
    }//GEN-LAST:event_Jaq_CheckActionPerformed

    private void Berm_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Berm_CheckActionPerformed
        if(Berm_Check.isSelected() == true){
            //Berm_Quant.setText("");
            Berm_Quant.setEditable(true);
            Berm_Quant.requestFocus(true);
        }
        else{
            Berm_Quant.setEditable(false);
            Berm_Quant.setText("0");
        }
    }//GEN-LAST:event_Berm_CheckActionPerformed

    private void Chinelo_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chinelo_CheckActionPerformed
        if(Chinelo_Check.isSelected() == true){
            //Chinelo_Quant.setText("");
            Chinelo_Quant.setEditable(true);
            Chinelo_Quant.requestFocus(true);
        }
        else{
            Chinelo_Quant.setEditable(false);
            Chinelo_Quant.setText("0");
        }
    }//GEN-LAST:event_Chinelo_CheckActionPerformed

    private void Bone_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bone_CheckActionPerformed
        if(Bone_Check.isSelected() == true){
            //Bone_Quant.setText("");
            Bone_Quant.setEditable(true);
            Bone_Quant.requestFocus(true);
        }
        else{
            Bone_Quant.setEditable(false);
            Bone_Quant.setText("0");
        }
    }//GEN-LAST:event_Bone_CheckActionPerformed

    private void Calc_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_TotalActionPerformed
        calctotal();
        if (RB_Vis.isSelected() == true){
            double totalDesc = SubTotal * 0.115;
            double total = SubTotal - totalDesc;
            Desc.setText(decimal.format(totalDesc));
            Total_Pag.setText(decimal.format(total));
            Tot_Parc.setText("0,00");
        }
        if(RB_Praz.isSelected() == true){
            if(SubTotal > 10){
                String parcelas = (String) Parc_Quant.getSelectedItem();
                double jurParc = Integer.parseInt(parcelas) * 6.90;
                double Porcentagem = SubTotal * 0.01;
                Desc.setText("0.00");
                double total_parcelado = SubTotal + Porcentagem + jurParc;
                Tot_Parc.setText(decimal.format(total_parcelado));
                Total_Pag.setText(decimal.format(total_parcelado));
            }
            if(SubTotal == 0){
                JOptionPane.showMessageDialog(this, "O Sub-total da compra não pode ser de R$0.00");
            }
            if(SubTotal < 10.00){
                JOptionPane.showMessageDialog(this,"O valor para opção de pagamento deve ser maior que R$10.00");
            }
        }
    }//GEN-LAST:event_Calc_TotalActionPerformed

    private void RB_PrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_PrazActionPerformed
        formaPag();
    }//GEN-LAST:event_RB_PrazActionPerformed

    private void RB_VisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_VisActionPerformed
       formaPag();
    }//GEN-LAST:event_RB_VisActionPerformed

    private void Meia_QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meia_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Meia_QuantActionPerformed

    private void Clear_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_AllActionPerformed
        Regata_Check.setSelected(false);
        Social_Check.setSelected(false);
        Blusa_Check.setSelected(false);
        Pullover_Check.setSelected(false);
        Sapato_Check.setSelected(false);
        Calca_Check.setSelected(false);
        Meia_Check.setSelected(false);
        Luva_Check.setSelected(false);
        Jaq_Check.setSelected(false);
        Berm_Check.setSelected(false);
        Chinelo_Check.setSelected(false);
        Bone_Check.setSelected(false);
        Regata_Quant.setEditable(false);
        Social_Quant.setEditable(false);
        Blusa_Quant.setEditable(false);
        Pullover_Quant.setEditable(false);
        Sapato_Quant.setEditable(false);
        Calca_Quant.setEditable(false);
        Meia_Quant.setEditable(false);
        Luva_Quant.setEditable(false);
        Jaq_Quant.setEditable(false);
        Berm_Quant.setEditable(false);
        Chinelo_Quant.setEditable(false);
        Bone_Quant.setEditable(false);
        Regata_Quant.setText("0");
        Social_Quant.setText("0");
        Blusa_Quant.setText("0");
        Pullover_Quant.setText("0");
        Sapato_Quant.setText("0");
        Calca_Quant.setText("0");
        Meia_Quant.setText("0");
        Luva_Quant.setText("0");
        Jaq_Quant.setText("0");
        Berm_Quant.setText("0");
        Chinelo_Quant.setText("0");
        Bone_Quant.setText("0");
        Tot_Regata.setText("0.00");
        Tot_Social.setText("0.00");
        Tot_Blusa.setText("0.00");
        Tot_Pullover.setText("0.00");
        Tot_Sapato.setText("0.00");
        Tot_Calca.setText("0.00");
        Tot_Meia.setText("0.00");
        Tot_Luva.setText("0.00");
        Tot_Jaq.setText("0.00");
        Tot_Berm.setText("0.00");
        Tot_Chinelo.setText("0.00");
        Tot_Bone.setText("0.00");
        Sub_Total.setText("0.00");
        Tot_Parc.setText("0.00");
        Desc.setText("0.00");
        Total_Pag.setText("0.00");
    }//GEN-LAST:event_Clear_AllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Calc_Financ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Calc_Financ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Calc_Financ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Calc_Financ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frm_Calc_Financ().setVisible(true);
            //if(Regata_Check.isSelected()){
            
            //}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Berm_Check;
    private javax.swing.JLabel Berm_Preco;
    private javax.swing.JTextField Berm_Quant;
    private javax.swing.JCheckBox Blusa_Check;
    private javax.swing.JLabel Blusa_Preco;
    private javax.swing.JTextField Blusa_Quant;
    private javax.swing.JCheckBox Bone_Check;
    private javax.swing.JLabel Bone_Preco;
    private javax.swing.JTextField Bone_Quant;
    private javax.swing.JButton Calc_Total;
    private javax.swing.JCheckBox Calca_Check;
    private javax.swing.JLabel Calca_Preco;
    private javax.swing.JTextField Calca_Quant;
    private javax.swing.JCheckBox Chinelo_Check;
    private javax.swing.JLabel Chinelo_Preco;
    private javax.swing.JTextField Chinelo_Quant;
    private javax.swing.JButton Clear_All;
    private javax.swing.JLabel Desc;
    private javax.swing.JLabel Desc_Label;
    private javax.swing.JPanel Financ_Painel;
    private javax.swing.JPanel For_Pag;
    private javax.swing.JCheckBox Jaq_Check;
    private javax.swing.JLabel Jaq_Preco;
    private javax.swing.JTextField Jaq_Quant;
    private javax.swing.JCheckBox Luva_Check;
    private javax.swing.JLabel Luva_Preco;
    private javax.swing.JTextField Luva_Quant;
    private javax.swing.JCheckBox Meia_Check;
    private javax.swing.JLabel Meia_Preco;
    private javax.swing.JTextField Meia_Quant;
    private javax.swing.JComboBox Parc_Quant;
    private javax.swing.JLabel Preco_Label;
    private javax.swing.JLabel Product_Label;
    private javax.swing.JCheckBox Pullover_Check;
    private javax.swing.JLabel Pullover_Preço;
    private javax.swing.JTextField Pullover_Quant;
    private javax.swing.JLabel Qt_Parc_Label;
    private javax.swing.JLabel Quant_Label;
    private javax.swing.JButton Quit_Button;
    private javax.swing.ButtonGroup RB_Formas;
    private javax.swing.JRadioButton RB_Praz;
    private javax.swing.JRadioButton RB_Vis;
    private javax.swing.JCheckBox Regata_Check;
    private javax.swing.JLabel Regata_Preco;
    private javax.swing.JTextField Regata_Quant;
    private javax.swing.JCheckBox Sapato_Check;
    private javax.swing.JLabel Sapato_Preco;
    private javax.swing.JTextField Sapato_Quant;
    private javax.swing.JCheckBox Social_Check;
    private javax.swing.JLabel Social_Preco;
    private javax.swing.JTextField Social_Quant;
    private javax.swing.JButton Sub_Button;
    private javax.swing.JLabel Sub_Label;
    private javax.swing.JLabel Sub_Total;
    private javax.swing.JLabel Tot_Berm;
    private javax.swing.JLabel Tot_Blusa;
    private javax.swing.JLabel Tot_Bone;
    private javax.swing.JLabel Tot_Calca;
    private javax.swing.JLabel Tot_Chinelo;
    private javax.swing.JLabel Tot_Jaq;
    private javax.swing.JLabel Tot_Luva;
    private javax.swing.JLabel Tot_Meia;
    private javax.swing.JLabel Tot_Parc;
    private javax.swing.JLabel Tot_Parc_label;
    private javax.swing.JLabel Tot_Pullover;
    private javax.swing.JLabel Tot_Regata;
    private javax.swing.JLabel Tot_Sapato;
    private javax.swing.JLabel Tot_Social;
    private javax.swing.JLabel Total_Financ_Lable;
    private javax.swing.JLabel Total_Label;
    private javax.swing.JLabel Total_Pag;
    // End of variables declaration//GEN-END:variables
}
